### 8.1.1 쓰기작업시 엘라스틱서치 동작과 동시성 제어
### 인덱스 생성
PUT /concurrency_test
Host: localhost:9200
Content-Type: application/json

{
  "settings": {
    "number_of_shards": 2
  }
}

### 문서 색인
PUT /concurrency_test/_doc/1
Host: localhost:9200
Content-Type: application/json

{
  "views": 1
}

### 문서 색인
PUT /concurrency_test/_doc/1?if_primary_term=1&if_seq_no=1
Host: localhost:9200
Content-Type: application/json

{
  "views": 3
}

### 버전
PUT /concurrency_test/_doc/10
Host: localhost:9200
Content-Type: application/json

{
  "views": 0
}

### 버전 external 지정
PUT /concurrency_test/_doc/10?version=15&version_type=external
Host: localhost:9200
Content-Type: application/json

{
  "views": 1
}

### 버전 external 지정
PUT /concurrency_test/_doc/10?version=13&version_type=external
Host: localhost:9200
Content-Type: application/json

{
  "views": 1
}
