spring:
  config:
    activate:
      on-profile: jasypt

jasypt:
  encryptor:
    bean: jasyptEncryptor
    password: ${JASYPT_PASSWORD}

--- # local
spring.config.activate.on-profile: local

jasypt:
  encryptor:
    bean: jasyptEncryptor
    password: test
