spring:
  application:
    name: starter-es
  messages:
    encoding: UTF-8
  profiles:
    include:
      - jasypt
      - common
      - security

server:
  port: 9903
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
  tomcat:
    accesslog:
      enabled: true
      directory:
      prefix: user.access-log
    basedir: logs/tomcat/user/

springdoc:
  packagesToScan: com.starter.es.app
  api-docs:
    enabled: true
    path: /document/api-docs
  swagger-ui:
    enabled: true
    path: /document/swagger-ui.html
